### PR TITLE
Avoid unecessary dependency on pytest-aiohttp module

### PR DESCRIPTION
**Pull request by eLvErDe**
If you look at the pytest-aiohttp module you will see it contains no code, it is just a wrapper silently doing the single line of this PR ;-)

### CODE REVIEW

**Comment by hzlmn** [comment]
But why? :) With this dependency we abstract away from implementation that might change in future. Also it is recommended way for doing testing by aiohttp author :)

**Comment by hzlmn** [comment]
Anyway thanks for your efforts

**Comment by eLvErDe** [comment]
Well that's one less package to create and clearly it's doing nothing but this. If you consider one day having this package in Debian or Ubuntu official repository there's absolutely **NO WAY** to depends on a package like pytest-aiohttp, it will never be accepted as it contains absolutely nothing.
If so the package will be patched the way I did :p

**Comment by hzlmn** [comment]
Do I understand you correct - you package each dependency as a debian package, right?

**Comment by eLvErDe** [comment]
Yup

**Comment by hzlmn** [comment]
Sorry, but this should be closed. It is very limited case and backporting internals of another package that may change  in future is not a good idea as for me.

**Pull request closed without merging**
