### PR TITLE
Setting attribute updated

### PR DESCRIPTION
**Pull request by shmidtelson**
In real life (python 3.9.1) this row doesnt work
Its problem with compatibility? Maybe

### CODE REVIEW

**Comment by hzlmn** [comment]
Hi, which version of aiohttp do you use? Could you send stacktrace of error you are getting.

**Comment by shmidtelson** [comment]
AioHTTP == 3.7.4.post0
image
Screen Shot 2021-03-19 at 14 51 06
I dont have errors. 
Problem is attribute doesnt setup

**Comment by hzlmn** [comment]
How do you access the property? could you provide code snippets?

**Comment by shmidtelson** [comment]
@hzlmn oh! thank you! it was my bad!

**Pull request closed without merging**
