### PR TITLE
Make unittests compatible with aiohttp 2.x

### PR DESCRIPTION
**Pull request by eLvErDe**
Follow Up of https://github.com/hzlmn/aiohttp-jwt/issues/26
Confirmed it fixes the test run on my system

### CODE REVIEW

**Comment by hzlmn** [comment]
Thanks but it won't work in env where `aiohttp_client` fixture presented. I guess the easiest way just to use test_client fixture everywhere instead of aiohttp_client. It should work fine on older and new versions.

**Comment by eLvErDe** [comment]
Indeed, that's an issue... We should define this function only is it does not exist yet, not sure how to do this.
I guess we should run hasattr against aiohttp pytest module or something like this, what you think ?

**Comment by hzlmn** [comment]
Something like this should work fine
```python
try:
    from pytest_aiohttp import aiohttp_client
except ImportError:
    @pytest.fixture
    def aiohttp_client(test_client):
        return test_client
```
Or you can track version of aiohttp and do the same but i think it is more "safe" way.

**Comment by hzlmn** [comment]
Closing this. Feel free to open an issue for further questions.

**Pull request closed without merging**
